version: '3.7'
services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros-${HOSTNAME}
    hostname: ${HOSTNAME}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
     - CLEANUP=true
     - LOG_LEVEL=info
     - SELF_UPDATE=true
     - TZ=${TIMEZONE}
     - CRON="${CRON}"

  letsencrypt:
    image: linuxserver/swag:latest
    container_name: letsencrypt-${HOSTNAME}
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${UID}
      - PGID=${UID}
      - TZ=${TIMEZONE}
      - URL=${HOSTNAME}
      - VALIDATION=http
    volumes:
      - /opt/adguard/letsencrypt-config:/config
    ports:
      - 80:80

  adguard:
     image: adguard/adguardhome:latest
     restart: always
     container_name: adguard-${HOSTNAME}
     hostname: ${HOSTNAME}
     network_mode: "host"
     environment:
      - TZ=${TIMEZONE}
     volumes:
      - /opt/adguard/work:/opt/adguardhome/work
      - /opt/adguard/conf:/opt/adguardhome/conf
      - /opt/adguard/letsencrypt-config/etc/letsencrypt:/le-ssl:ro
     depends_on:
      - unbound
      
  unbound:
     image: klutchell/unbound:latest
     restart: always
     container_name: unbound-${HOSTNAME}
     volumes:
      - /opt/adguard/adguard-unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - /opt/adguard/root.hints:/opt/unbound/etc/unbound/root.hints
     ports:
      - "5353:53/tcp"
      - "5353:53/udp"
